[versions]
kfswatch = "1.4.0"
knotify = "0.4.3"
kotlinMultiplatformAppdirsVersion = "2.0.0"
kotlinx-coroutines = "1.11.0"
nucleusSystem = "2.4.7"
javase = "3.5.4"
connectivity = "2.5.1"
camerak = "1.2"
ksafe = "3.0.0"

[libraries]
core = { module = "com.google.zxing:core", version.ref = "javase" }
github-nucleus-notifications-common = { module = "dev.nucleusframework:nucleus.notification-common", version.ref = "nucleusSystem" }
github-nucleus-scheduler = { module = "dev.nucleusframework:nucleus.scheduler", version.ref = "nucleusSystem" }
github-nucleus-scheduler-testing = { module = "dev.nucleusframework:nucleus.scheduler-testing", version.ref = "nucleusSystem" }
github-nucleus-taskbar-progress = { module = "dev.nucleusframework:nucleus.taskbar-progress", version.ref = "nucleusSystem" }
nucleus-core-runtime = { module = "dev.nucleusframework:nucleus.core-runtime", version.ref = "nucleusSystem" }
nucleus-aot-runtime = { module = "dev.nucleusframework:nucleus.aot-runtime", version.ref = "nucleusSystem" }
nucleus-updater-runtime = { module = "dev.nucleusframework:nucleus.updater-runtime", version.ref = "nucleusSystem" }
nucleus-nucleus-application = { module = "dev.nucleusframework:nucleus.nucleus-application", version.ref = "nucleusSystem" }
javase = { module = "com.google.zxing:javase", version.ref = "javase" }
kfswatch = { module = "io.github.irgaly.kfswatch:kfswatch", version.ref = "kfswatch" }
knotify = { module = "io.github.kdroidfilter:knotify", version.ref = "knotify" }
kotlin-multiplatform-appdirs = { module = "ca.gosyer:kotlin-multiplatform-appdirs", version.ref = "kotlinMultiplatformAppdirsVersion" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
nucleus-system-color = { module = "dev.nucleusframework:nucleus.system-color", version.ref = "nucleusSystem" }
nucleus-system-info = { module = "dev.nucleusframework:nucleus.system-info", version.ref = "nucleusSystem" }
connectivity-http = { module = "dev.jordond.connectivity:connectivity-http", version.ref = "connectivity" }
camerak = { module = "io.github.kashif-mehmood-km:camerak", version.ref = "camerak" }
camerak-image-saver = { module = "io.github.kashif-mehmood-km:image_saver_plugin", version.ref = "camerak" }
camerak-qr-scanner = { module = "io.github.kashif-mehmood-km:qr_scanner_plugin", version.ref = "camerak" }
camerak-ocr = { module = "io.github.kashif-mehmood-km:ocr_plugin", version.ref = "camerak" }
camerak-analyzer = { module = "io.github.kashif-mehmood-km:analyzer_plugin", version.ref = "camerak" }
ksafe-biometrics = { module = "eu.anifantakis:ksafe-biometrics", version.ref = "ksafe" }

[bundles]
